language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: knEhn+ZABg/k7YluGkwz5+o8+4/MNwNRF+qoP2Gu2RmF0/KK/jdqlMf9BoDjqzDhs60kA8FxfaYKgzAM2lsC41tCSZ9fhytvBU7spxN+XVXAebJN5n4E5QKPXOsklK1RB/+71V9psV500QvyMtBFz3ldB38T4B1FQVJDNpFEc8UDxE12aK9cX38PtBRcKzMyTjJjpAvG3cOtf9AE9Hs+nJg3p91wCSBm+kQzWp1Jn3SQ4hB6oc3lufAsHPoZl9ErNbqeQWHqcn4GTdpSvFQtOzi1Y4U3ASbiHQtYygrDaqKNZ4VisTlPk5l6D/sbnvO9ULqP9Gx8a8DdBkUpIKq34NNF2cQaDM3dNCT27mDuU30X13rtrH9W4f7YmHPnqd7Xa9LfZ1VDgnDwoxTwqBQ0n/gpxglWutJz1aesI3fClDnqDNjGBVkJh0H3t4v1DRetsNFGoW9vIHn8vG5l9UpjhuGtFxGX1JO3h7Ju0xrQVRIbIrcbmD8Ig2PfrAeZyaTifjUWulVRK3Bp18lmMKcHNqETeMvuQJakKcj3lKiWm6lYB0VnVj4vgIPJzxrRbo1UJrHRxfzNL0Q2IS00lndoaxMGZV9tuqfuPDkawwS82yVyEFHMxZPa+7yL9rOnKe+5scSZT7KUhVMvGCPlukK9OLPMMfXPlTjUXHREqIU+JFw=
  run: rails db:migrate
